@extends('app')

@section('content')
<div class="container card">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit, est eu placerat fringilla, lorem augue ullamcorper lectus, et luctus arcu mi non lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam vehicula iaculis odio quis fermentum. In rutrum lacinia dolor vitae venenatis. In hac habitasse platea dictumst. Suspendisse ultricies ac dolor vel tincidunt. Nam neque sem, bibendum quis lectus id, condimentum ornare urna. Praesent vestibulum dictum pellentesque. Phasellus varius scelerisque mi, at aliquam nisi suscipit ut. Nullam non eros porta, egestas nunc cursus, dignissim sapien. Fusce turpis urna, malesuada sed risus nec, auctor venenatis tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam vitae velit a urna iaculis maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In in euismod neque. In eget urna ut dolor sodales dignissim ac vitae ante.
<br /><br />
Pellentesque orci arcu, feugiat eget turpis sed, feugiat euismod risus. Donec nec sapien vitae eros imperdiet accumsan. Aenean cursus nulla sollicitudin orci elementum tempor. Praesent malesuada tincidunt ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse malesuada ac risus a iaculis. Nullam vitae felis orci. Cras consectetur euismod odio non scelerisque. Vestibulum dapibus cursus scelerisque. Suspendisse potenti. Pellentesque ante est, commodo non ligula eu, venenatis dapibus odio.
<br /><br />
Ut rutrum ipsum dui, eget tempor tellus tempor in. Vestibulum eros ipsum, dictum non turpis iaculis, mattis lacinia urna. Donec ac sodales dui. Nam vulputate arcu non urna maximus mattis. Fusce sit amet erat lorem. Morbi nisl sem, laoreet sit amet metus non, pharetra euismod velit. Morbi dapibus vulputate tortor, et luctus turpis pretium id. Nunc tempus eleifend nisl id accumsan. Curabitur tempus sit amet lorem non blandit. Aliquam eget maximus lorem. Curabitur rutrum nunc sed est viverra facilisis.
<br /><br />
Nam dolor orci, sagittis ac luctus vel, feugiat sit amet justo. Integer ac dolor vel purus faucibus finibus et ac leo. Donec eu ante congue, semper leo non, convallis leo. Praesent tellus ex, molestie a pulvinar sed, suscipit nec tellus. Etiam sed arcu varius, maximus mi ac, euismod purus. Suspendisse eu purus augue. Suspendisse nec erat interdum, finibus elit ac, faucibus elit. Proin facilisis, mi sed pretium pellentesque, enim nibh bibendum eros, in molestie enim leo a ipsum. Aliquam imperdiet ipsum vel massa scelerisque, tempus tempor dolor elementum. Donec viverra fringilla lorem vel pellentesque. Cras quis nibh pellentesque augue mattis imperdiet. Aliquam eu libero sed dolor convallis rutrum. Praesent rutrum arcu at velit porta pellentesque. Sed congue, est feugiat mollis luctus, ligula enim porta felis, et dictum odio est sed nunc. Mauris sed lectus ac nisl rhoncus volutpat quis sit amet tellus.
<br /><br />
Mauris id porta libero. Mauris vulputate sollicitudin volutpat. Aenean tristique odio nunc, at porta augue finibus at. Mauris eleifend volutpat leo vel luctus. Fusce faucibus leo et orci suscipit bibendum. Vivamus nibh ligula, feugiat vel tellus in, mattis facilisis nibh. Nunc viverra felis at lacinia facilisis. Vestibulum pulvinar nisi a efficitur posuere.


</div>
@endsection
